# Generated by Django 3.2.9 on 2021-11-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
