# Generated by Django 3.2.9 on 2021-11-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20211130_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
