# Generated by Django 3.2.9 on 2021-11-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_background_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
