# Generated by Django 3.2.9 on 2021-12-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(default='/static/images/default_profile_pic.jpeg', max_length=255),
        ),
    ]
